[package]
name = "bin-proto"
version = "0.3.3"
authors = [
    "Wojciech Graj <wojtek.graj.2004@gmail.com>",
    "Dylan McKay <me@dylanmckay.io>"
]
edition = "2018"

description = "Easy binary protocol definitions"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/wojciech-graj/bin-proto"
documentation = "https://docs.rs/bin-proto"
keywords = ["protocol", "binary", "bit", "codec", "serde"]

[features]
default = ["derive"]
derive = ["bin-proto-derive"]

[dependencies]
bin-proto-derive = { version = "0.3.1", path = "../bin-proto-derive", optional = true }
bitstream-io = "2.2.0"
thiserror = "1.0.58"
