[package]
name = "bin-proto-derive"
version = "0.4.0"
authors = [
    "Wojciech Graj <wojtek.graj.2004@gmail.com>",
    "Dylan McKay <me@dylanmckay.io>"
]
edition = "2021"

description = "Derive macros for bin-proto"
license = "MIT"
repository = "https://github.com/wojciech-graj/bin-proto"
documentation = "https://docs.rs/bin-proto"
keywords = ["protocol", "binary", "bit", "codec", "serde"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.109", features = ["default", "extra-traits", "fold"] }
quote = "1.0.35"
proc-macro2 = "1.0.79"
